# Generated by Django 3.2.7 on 2021-12-26 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Person_app', '0006_delete_role'),
        ('Series_app', '0002_series_series_hits'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='series',
            name='language',
        ),
        migrations.RemoveField(
            model_name='series',
            name='quality',
        ),
        migrations.RemoveField(
            model_name='series',
            name='screen_shot',
        ),
        migrations.RemoveField(
            model_name='series',
            name='size',
        ),
        migrations.RemoveField(
            model_name='series',
            name='subscription',
        ),
        migrations.RemoveField(
            model_name='series',
            name='subtitle',
        ),
        migrations.AddField(
            model_name='series',
            name='cast',
            field=models.ManyToManyField(blank=True, related_name='series_cast', to='Person_app.Person'),
        ),
        migrations.AddField(
            model_name='series',
            name='creator',
            field=models.ManyToManyField(blank=True, related_name='series_creator', to='Person_app.Person'),
        ),
    ]
