# Generated by Django 3.2.7 on 2021-12-29 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Series_app', '0003_auto_20211226_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='imdb_rate',
            field=models.CharField(max_length=100),
        ),
    ]
