# Generated by Django 3.2.7 on 2021-12-29 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Series_app', '0004_alter_series_imdb_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='imdb_rate',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
