# Generated by Django 3.2.7 on 2021-12-29 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Series_app', '0005_alter_series_imdb_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='series',
            name='release_date',
        ),
    ]
