# Generated by Django 3.2.7 on 2021-12-29 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Series_app', '0006_remove_series_release_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='release_date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
