# Generated by Django 3.2.7 on 2021-12-30 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Series_app', '0008_series_imdb_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='series',
            name='seasons',
        ),
    ]
