# Generated by Django 3.2.7 on 2021-12-30 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Series_app', '0009_remove_series_seasons'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Season',
        ),
    ]
