# Generated by Django 3.2.7 on 2021-12-26 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Person_app', '0006_delete_role'),
        ('Movie_app', '0002_movie_movie_hits'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='background_image_link',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='language',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='link_1920',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='link_4k',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='link_720',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='movie_link',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='movie_online',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='premium',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='screen_shot',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='screen_shot_link',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='size_1920',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='size_4k',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='size_720',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='subtitle',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='thumbnail_link',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='tmv_db_id',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='torrent_file_link',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='torrent_link_1920',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='torrent_link_4k',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='torrent_link_720',
        ),
        migrations.AddField(
            model_name='movie',
            name='cast',
            field=models.ManyToManyField(blank=True, related_name='movies_cast', to='Person_app.Person'),
        ),
        migrations.AddField(
            model_name='movie',
            name='director',
            field=models.ManyToManyField(blank=True, related_name='movies_director', to='Person_app.Person'),
        ),
    ]
