# Generated by Django 3.2.7 on 2021-12-30 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movie_app', '0003_auto_20211226_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='imdb_link',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
    ]
