# Generated by Django 3.2.7 on 2021-12-26 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movie_app', '0002_movie_movie_hits'),
        ('Series_app', '0002_series_series_hits'),
        ('Person_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='role',
            field=models.CharField(choices=[('CAST', 'cast'), ('DIRECTOR', 'director')], default='cast', max_length=140),
        ),
        migrations.AlterUniqueTogether(
            name='role',
            unique_together={('movie', 'series', 'role')},
        ),
        migrations.RemoveField(
            model_name='role',
            name='name',
        ),
    ]
