# Generated by Django 3.2.7 on 2021-12-26 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Person_app', '0002_auto_20211226_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='role',
            field=models.ManyToManyField(blank=True, related_name='persons_role', to='Person_app.Role'),
        ),
        migrations.AlterField(
            model_name='role',
            name='person',
            field=models.ManyToManyField(blank=True, related_name='role_person', to='Person_app.Person'),
        ),
        migrations.AlterField(
            model_name='role',
            name='role',
            field=models.CharField(choices=[('CAST', 'cast'), ('DIRECTOR', 'director'), ('CREATOR', 'creator')], default='cast', max_length=140),
        ),
    ]
