# Generated by Django 3.2.7 on 2021-12-26 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Person_app', '0004_auto_20211226_1333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='role',
        ),
        migrations.AlterField(
            model_name='role',
            name='person',
            field=models.ManyToManyField(blank=True, to='Person_app.Person'),
        ),
    ]
