# Generated by Django 3.2.7 on 2021-12-26 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Person_app', '0005_auto_20211226_1335'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Role',
        ),
    ]
