# Generated by Django 3.2.7 on 2022-01-02 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screenshot',
            name='uploaded',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
