# Generated by Django 3.2.7 on 2022-01-02 12:40

import Main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_alter_screenshot_uploaded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screenshot',
            name='image',
            field=models.FileField(upload_to=Main.models.screen_shot_upload_to),
        ),
    ]
