# Generated by Django 3.2.7 on 2021-12-25 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Movie_app', '0001_initial'),
        ('User_IP', '0001_initial'),
        ('Series_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HitModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='User_IP.ipaddress')),
                ('movie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Movie_app.movie')),
                ('series', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Series_app.series')),
            ],
        ),
    ]
